# Generated by Django 2.2 on 2020-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description odndsn;jnb vjfipfsbak;a  fndas;fn'),
            preserve_default=False,
        ),
    ]
